version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: migrate
      POSTGRES_DB: migrate
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data

networks:
  default:
    name: golang-migrate-example